conditioning: Use core-provided libraries instead of dangling symlinks
libraries .so files provided by -dev packages normally point to the
versioned so file, but if these files are provided by the core snap or
another base snap then we should instead use them, if they're not
provided by the SDK itself.

So, ensure that all the symlinks in the lib directory are actually
pointing to a library file, trying to resolve them with the
core-provided libraries as first try.

diff --git a/snapcraft.yaml b/snapcraft.yaml
--- a/snapcraft.yaml
+++ b/snapcraft.yaml
@@ -1637,10 +1637,27 @@ parts:
       ln -s gettext-0.19.8 usr/share/gettext-current
       ln -s gdk-pixbuf-2.0/2.10.0 usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gdk-pixbuf-current
 
-      # Fix dangling symlink by overwriting it
-      ln -sf lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libc_malloc_debug.so.0 usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libc_malloc_debug.so
-      # CHECK THIS When changing the core base, this line must be update
-      cp /snap/$CRAFT_EXT_CORE_LEVEL/current/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libc_malloc_debug.so.0 lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/
+      # Check dangling libraries symlinks
+      invalid_links=()
+      core_root_prefix=/snap/$CRAFT_EXT_CORE_LEVEL/current
+      for i in $(find "$CRAFT_PRIME"/{usr/,}lib -xtype l -name '*.so'); do
+        # Try fix dangling symlink by overwriting it with core library if any.
+        rel_lib_path=$(realpath --relative-to="$CRAFT_PRIME" "$i")
+        core_lib=$core_root_prefix/$(dirname "$rel_lib_path")/$(readlink "$i")
+
+        if realpath --canonicalize-existing "$core_lib"; then
+          ln -svf "${core_lib#"$core_root_prefix"}" "$i"
+          continue
+        fi
+
+        echo "$i: dangling symlink!"
+        invalid_links+=($i)
+      done
+      if [ ${#invalid_links[@]} -gt 0 ]; then
+        echo "Invalid symlinks found:"
+        echo "${invalid_links[@]}"
+        exit 1;
+      fi
 
       # Necessary for armhf builds, triggers review warning
       if [ "$CRAFT_ARCH_TRIPLET_BUILD_FOR" = "arm-linux-gnueabihf" ]; then
